services:
  - type: web
    name: amazon-clone-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/products
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
